### PR TITLE
fix setting today class

### PR DESCRIPTION
**Pull request by ryanrasmussen05**
If highlight days are not set, still set the 'today' class on todays date.

Also, fix appending 'today' class onto highlightDay class if highlightDays includes today

### CODE REVIEW

**Comment by ryanrasmussen05** [comment]
@xtianus79 have you reviewed this?  We'd love to get this merged as we are using this for a contract that's nearing prod

**Comment by ryanrasmussen05** [comment]
ping

**Comment by ryanrasmussen05** [comment]
ping @xtianus79

**Comment by xtianus79** [comment]
@ryanrasmussen05 I merged your fix in. I really need to get back on top of this.

**Pull request merged**
